### ISSUE TITLE
DE pattern

### ISSUE THREAD

**Issue by Seara** [bluejamesbond/TextJustify-Android#108]
Hi there! There is a missing pattern for German language in class DefaultHyphenator in gradle. Could you please update it?

**Comment by bluejamesbond** [comment]
Thank you for bringing this up. Should be addressed in [2.1.6](https://github.com/bluejamesbond/TextJustify-Android/blob/master/library/src/main/java/com/bluejamesbond/text/hyphen/DefaultHyphenator.java#L219)
