### ISSUE TITLE
I didn't get full text when I scroll my app.

### ISSUE THREAD

**Issue by vinod023** [bluejamesbond/TextJustify-Android#118]
Sir, I am using Textjustify class. it works fine textview in english language. it is not compatible with other language (telugu). when scroll my app some lines are missing from the bottom. plz help me...thanking you....

**Comment by bluejamesbond** [comment]
Try manipulating the `ext:documentView_insetPaddingBottom`

**Comment by vinod023** [comment]
thank you sir. I got the solution.
