### ISSUE TITLE
Spannable TextView with different colors

### ISSUE THREAD

**Issue by andresgr** [bluejamesbond/TextJustify-Android#21]
Given the following program:

TextViewEx textView = (TextViewEx) findViewById(R.id.textView1);
textView.setText("", true);
Spannable span = Spannable.Factory.getInstance().newSpannable("Hello ");
span.setSpan(new ForegroundColorSpan(Color.RED), 0, span.length(),
                  Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
span = Spannable.Factory.getInstance().newSpannable(" world!");
span.setSpan(new ForegroundColorSpan(Color.GREEN), 0, span.length(),
                  Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);

The output text is printed without any red or green color. Is there any way to solve the justifying of a TextViewEx with different styles?

**Comment by Edonfreiner** [comment]
This is still not working for me how do I change the background of the DocumentView?
