### ISSUE TITLE
Upload to maven central?

### ISSUE THREAD

**Issue by ened** [bluejamesbond/TextJustify-Android#38]
Are you planning to upload this neat library to Maven Central? It would certainly make it more accessible for new developers to include the project with a one-liner in their gradle config. :)

**Comment by bluejamesbond** [comment]
```gradle
compile 'com.github.bluejamesbond:textjustify-android:2.0.1'
```

**Comment by DjBushido** [comment]
Awesome, thanks for this! So excited to start using it.
