### ISSUE TITLE
how do we use with page curl?

### ISSUE THREAD

**Issue by Jamshidbek** [bluejamesbond/TextJustify-Android#39]
how we use with https://github.com/harism/android_page_curl ?
pls, advice me how can i implement for page curl?

**Comment by Jamshidbek** [comment]
so, how can i use your view instead of textView?

**Comment by bluejamesbond** [comment]
I don't think we have compatibility at this point. You would need to mess with the code a bit

**Comment by Jamshidbek** [comment]
first, we get device height, calculate text for the height (calculating via textview), end, set the text to textView

//setting text to the textView
        tv.setGravity(Gravity.LEFT | Gravity.RIGHT);
        CharSequence text = buffer.getTextbuffer().subSequence(start, end);
        if (text != null && text.length() > 0 && (text.charAt(0) == '\n' || text.charAt(0) == ' ')) {
            text = text.subSequence(1, text.length());
        }
        try {
            tv.setText(text, TextView.BufferType.SPANNABLE);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        tv.draw(canvas);

**Comment by bluejamesbond** [comment]
Let me look at it this evening

**Comment by Jamshidbek** [comment]
ok, thanks for your time

**Comment by bluejamesbond** [comment]
@Jamshidbek Ok. I went through your code and I see that what your doing. Basically, you are telling TextView to draw the contents. So, in the TextJustify code in the latest build also relies on something called the DocumentLayout (similar to StaticLayout) to develop and organize the text. You can then do something like `documentLayout.draw(canvas)`. But this will draw all the text onto the canvas whether or not the content has gone beyond the canvas; which is inefficient for long text like books. So in the TextJustify build that should be coming out in the next few days, you will be able to do `documentLayout.draw(canvas, startY, startY + height)` which will be highly efficient. So hold on two more days and I will show some sample code here.

**Comment by Jamshidbek** [comment]
Ok. Thank you @bluejamesbond.

**Comment by bluejamesbond** [comment]
Ok so if you want to render one page to a Bitmap, here is how you do it. It should work for PageCurl as well.

```java
// Page dimensions
float pageHeight = 600;
float pageWidth = 400;

// Create and setup layout
IDocumentLayout documentLayout = new StringDocumentLayout(this, new TextPaint());
documentLayout.setText("Large text input");
documentLayout.getLayoutParams().setParentWidth(pageWidth);
documentLayout.measure(new IDocumentLayout.ISet<Float>() {
    @Override
    public void set(Float val) {
        Log.d("progress", val.toString());
    }
}, new IDocumentLayout.IGet<Boolean>() {
    @Override
    public Boolean get() {
        return true; // don't ever cancel the process
    }
});

// Create bitmap
Bitmap bitmap = Bitmap.createBitmap((int) pageWidth, (int) pageHeight, Bitmap.Config.ARGB_8888);

// If you only want text between 30 and 100
int drawStartY = 30;
int drawEndY = 100;
documentLayout.draw(new Canvas(bitmap), drawStartY, drawEndY);
```

**Comment by Jamshidbek** [comment]
@bluejamesbond Thank you! Thank you for the great job!
i have one question. in initializing, 
        Resources resources = getApplicationContext().getResources();
        DisplayMetrics metrics = resources.getDisplayMetrics();
        bitmapHeight = metrics.heightPixels;
        bitmapWidth = metrics.widthPixels / i;
        textview.layout(0, 0, bitmapWidth, bitmapHeight);

without layout mehtod, don't show in my app,
how can i apply layout method for documentLayout?

**Comment by bluejamesbond** [comment]
Can you clarify the question. I don't understand. 



—

**Comment by bluejamesbond** [comment]
@Jamshidbek 

You should try this:

```java
int drawStartY = 0; // Make sure to put this to 0
int drawEndY = 100;
documentLayout.draw(new Canvas(bitmap), drawStartY, drawEndY);
```

**Comment by Jamshidbek** [comment]
@bluejamesbond 

I tried it. But it does'nt work

**Comment by bluejamesbond** [comment]
@Jamshidbek Sorry, I made a mistake in my code

Change:

```
return true; // don't ever cancel the process
``
```
return false; // don't ever cancel the process
```

**Comment by Jamshidbek** [comment]
@bluejamesbond 
thank you! it's working!!!

**Comment by bluejamesbond** [comment]
np

**Comment by jamshid88** [comment]
if i give 0 to drawEndY (startTop) and drawEndY(startBottom), nothing changed. (build: 2.0.4)

// If you only want text between 30 and 100
int drawStartY = 30;
int drawEndY = 100;
documentLayout.draw(new Canvas(bitmap), drawStartY, drawEndY);
