### ISSUE TITLE
Bold does not work ...

### ISSUE THREAD

**Issue by Shuhrat-java** [bluejamesbond/TextJustify-Android#40]
Hello I am giving spannable text to justify on FormattedTextTest class , but following to method calls I found that there is  
 public void setText(CharSequence text) {
        this.text = text.toString();
        this.textChange = true;
 }
in DocumentLayout class that will destroy all spannable text settings and make it plain text. Or am I wrong somewhere?

**Comment by Edonfreiner** [comment]
How does one use the SpannableDocumentLayout?
