### ISSUE TITLE
Hyphenation

### ISSUE THREAD

**Issue by muriloandrade** [bluejamesbond/TextJustify-Android#41]
Hi,
I saw you made some amazing improvements in the new version of TextJustify, including the hyphenation, congratulations.

Now I’m trying to implement this new version into my project but I’m facing an issue.

If I right understand, the new way to get texts hyphenatated is:

```
docView.getDocumentLayoutParams().setHyphenator(new Hyphenator(HyphenPattern.PT));
docView.getDocumentLayoutParams().setHyphenated(true);
```

This way, nothing happens, seems like `LayoutParams.setHyphenator()` method will always just return (without set).
So I made some changes in this method and have the hyphenator settled.

But now, I’m facing an Exception:

java.util.ConcurrentModificationException
            at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
            at com.bluejamesbond.text.DocumentLayout.measure(DocumentLayout.java:222)
            at com.bluejamesbond.text.DocumentView.onMeasure(DocumentView.java:142) …

Let me know if you need more details. Thank you.

**Comment by muriloandrade** [comment]
Thank you for the fix.
But now I'm getting the text justified but not hyphenated.
I may be missing a step, so, no rush, but can you provide me an example on how to use?
Thank you again.

**Comment by bluejamesbond** [comment]
@muriloandrade It does hyphenate. I have put your exact code into the the sample demo which you can download at https://play.google.com/store/apps/details?id=com.bluejamesbond.text.sample

Just click on the "Hyphenated Test"
