### ISSUE TITLE
Line is truncated

### ISSUE THREAD

**Issue by lucastan** [bluejamesbond/TextJustify-Android#46]
![screenshot_2015-01-05-02-21-56](https://cloud.githubusercontent.com/assets/742503/5606960/efdb6fe6-9481-11e4-987b-3465e9d5cbcb.png)

The first line is truncated (The letter P is cut off) on API 15,  lib 1.4

XML as follows:
```xml
<com.bluejamesbond.text.DocumentView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="xxx"
            android:textAppearance="@style/TextAppearance.AppCompat.Body1"
            document:antialias="true"
            document:textSubpixel="true"
            document:textAlignment="justified"
            document:textFormat="plain"
            document:textSize="@dimen/abc_text_size_body_1_material"
            document:textColor="@color/abc_primary_text_material_light"
            document:text="xxxx" />

**Comment by bluejamesbond** [comment]
Can you give me the whole text?

**Comment by lucastan** [comment]
Please create an account to receive app updates and the
        hottest deals and promotions. We will keep your information strictly confidential.

**Comment by bluejamesbond** [comment]
Make an account where? 



—

**Comment by bluejamesbond** [comment]
lol. I thought this was a spam question from your text. I'll look at it when I get back

**Comment by bluejamesbond** [comment]
Did you add padding?

**Comment by bluejamesbond** [comment]
Thanks. Its fixed!
```gradle
compile 'com.github.bluejamesbond:textjustify-android:1.5'
```

**Comment by lucastan** [comment]
thanks! it works perfectly :)

some suggestions:
- tag your git branch with '1.5' so people can refer to it.
- compile with target SDK == 21 (latest) as google suggested.

**Comment by bluejamesbond** [comment]
@lucastan Thanks for the tips

The compile settings are as follows. Let me see if you see anything wrong.
```gradle
    compileSdkVersion 21
    buildToolsVersion '21.1.2'
    defaultConfig {
        minSdkVersion 8
        targetSdkVersion 8
        versionCode 2
        versionName '2.0'
    }
```

**Comment by bluejamesbond** [comment]
@lucastan I accidentally deleted your comment. But thanks for the tip!
