### ISSUE TITLE
Prefix all the customs attrs

### ISSUE THREAD

**Issue by pdegand** [bluejamesbond/TextJustify-Android#52]
As you are using rather common custom attrs like `text` or `textSize`, theses attrs could conflict with another libraries.

As suggested by Xavier Ducrohet [here](https://groups.google.com/d/msg/adt-dev/HeM0aptfddY/R8a18AwE7MQJ), you should prefix all your custom attrs with something like `tj_`.

You could also consider using the platform attrs for common attrs like `textSize`, `padding`etc...

Thanks

**Comment by bluejamesbond** [comment]
Thank you. Improvements will be put in the next build.

**Comment by bluejamesbond** [comment]
Done. Version 2.0.3. Prefixed with `documentView`
