### ISSUE TITLE
IndexOutOfBoundsException while measuring...

### ISSUE THREAD

**Issue by Shuhratjava** [bluejamesbond/TextJustify-Android#55]
Hello,
I have android 2.3.6 phone device. Sometimes I get IndexOutOfBoundsException on SpannableDocumentLayout class starting from the 230 line: 
// Use the line-height of the next line
                y += enableLineBreak * (-staticLayout.getLineAscent(lineNumber + 1) + staticLayout
                        .getLineDescent(lineNumber + 1));
I debug and see that error comes from staticLayout.getLineAscent(lineNumber + 1) part.

**Comment by bluejamesbond** [comment]
Can you provide me the version number?

**Comment by Shuhratjava** [comment]
Android version on my phone 2.3.6, SDK version 10

**Comment by bluejamesbond** [comment]
@Shuhratjava I meant the version of TextJustify

**Comment by Shuhratjava** [comment]
Version is 2.0.4

**Comment by bluejamesbond** [comment]
Interesting. Ill review it and let you know by tomorrow.

**Comment by bluejamesbond** [comment]
Try 2.0.5 and let me know
