### ISSUE TITLE
Khmer not support

### ISSUE THREAD

**Issue by bpbunthoeun** [bluejamesbond/TextJustify-Android#57]
Thank you so much for you library it is very helpful, but I got the problem when I use it with Khmer unicode. it doesn't working well. Can you please help me to to finger-out this problem.
Thank you.
Bunthoeun

![screen shot 2015-01-19 at 2 55 13 pm](https://cloud.githubusercontent.com/assets/4226547/5797449/b3490c5c-9fec-11e4-8902-1b97996f0539.png)
![screenshot_2015-01-19-15-04-37](https://cloud.githubusercontent.com/assets/4226547/5797450/b34946ae-9fec-11e4-81f8-a4ecd21c41ac.png)

**Comment by bluejamesbond** [comment]
It is because your words are too long. What you can try to do is increase the font size. Make sure to use DocumentView.FORMATTED_TEXT

**Comment by bpbunthoeun** [comment]
Here is my java : 

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        //DocumentView documentView = (DocumentView) findViewById(R.id.doc_view1);
        DocumentView documentView = new DocumentView(this, DocumentView.FORMATTED_TEXT);
        documentView.getDocumentLayoutParams().setHyphenator(new Hyphenator(HyphenPattern.PT));
        documentView.getDocumentLayoutParams().setHyphenated(true);
       
    }
}

But still get the same result.
Thank you.
Bunthoeun

**Comment by bluejamesbond** [comment]
Your words are too long. Give me a day or two to add support for this. 



—

**Comment by bpbunthoeun** [comment]
Yes thank you so much. I can give some string: សៀវភៅដំបូងដែលគ្រឹះស្ថាន «ប្រភពប្រាជ្ញា» បានបោះពុម្ពនោះ គឺជាស្នាដៃរបស់អ្នកនិពន្ធ ប៉ែន តារាឫទ្ធិ ដែលជាការបកស្រាយអំពីកណ្ឌអេភេសូរ។ ទោះបើអ្នកប្រាជ្ញខាងគម្ពីរ និង អ្នកនិពន្ធរូបនេះ បានចែកឋានប៉ុន្មានអាទិត្យមុនពេល ដែលសៀវភៅនេះបានចែកចាយក៏ដោយ ក៏ស្នាដៃរបស់អ្នកនិពន្ធ ប៉ែន តារាឫទ្ធិ នៅតែដក់ជាប់ក្នុងចិត្តមនុស្សគ្រប់ជំនាន់ តាមរយៈសៀវភៅនេះដែរ។ បច្ចុប្បន្ននេះ «ប្រភពប្រាជ្ញា» មានទីតាំងនៅផ្ទះលេខ១១អា ផ្លូវលេខ២០០២ សង្កាត់ទឹកថ្លា ខណ្ឌសែនសុខ រាជធានីភ្នំពេញ។ មានបុគ្គលិកពេពេលជាជនជាតិខ្មែរ១១នាក់ សុទ្ធសឹងតែជាអ្នកមានជំនាញខ្ពស់ក្នុងវិស័យបោះពុម្ពផ្សាយ។ នោះជានិមិត្តចុងក្រោយរបស់លោកស្ទីវចំពោះ «ប្រភពប្រាជ្ញា» ដែលចង់ឃើញគ្រីស្ទបរិស័ទខ្មែរ ដឹកនាំពន្ធ័កិច្ចបោះពុម្ពផ្សាយដ៏សំខាន់នេះឆ្ពោះទៅពេលអនាគតដោយប្រសិទ្ធភាព។

**Comment by bluejamesbond** [comment]
@bpbunthoeun You can build your custom hyphenator for this. This way it will break the words at the right places. If you use the built in `SqueezeHyphenator`, then your words should fit better into one line. **Make sure** to use `DocumentView.PLAIN_TEXT` in order to achieve this and update to version `2.0.6`

```java
documentView.getDocumentLayoutParams().setTextAlignment(TextAlignment.JUSTIFIED);
documentView.getDocumentLayoutParams().setHyphenator(SqueezeHyphenator.getInstance());
documentView.getDocumentLayoutParams().setHyphenated(true);
```

If you are having trouble, refer to [CustomHyphenatorTest](https://github.com/bluejamesbond/TextJustify-Android/blob/master/sample/src/main/java/com/bluejamesbond/text/sample/test/CustomHyphenatorTest.java). Let me know how this goes for you.

**Comment by bpbunthoeun** [comment]
Dear Mathew, Thanks you very much for you answer, But I just get some error when use this DocumentView documentView = addDocumentView(new StringBuilder()
                .append(getResources().getString(R.string.zero_spacing))
                .toString(), DocumentView.PLAIN_TEXT);. I got red color on addDocumentView.

Here is my full java I just tries to copy your example come to test how it going: 

package com.cambobox.documentview;

import android.app.Activity;
import android.os.Bundle;

import com.bluejamesbond.text.DocumentView;
import com.bluejamesbond.text.hyphen.SqueezeHyphenator;
import com.bluejamesbond.text.style.TextAlignment;


public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        DocumentView documentView = addDocumentView(new StringBuilder()
                .append(getResources().getString(R.string.zero_spacing))
                .toString(), DocumentView.PLAIN_TEXT);

        documentView.getDocumentLayoutParams().setTextAlignment(TextAlignment.JUSTIFIED);
        documentView.getDocumentLayoutParams().setHyphenator(SqueezeHyphenator.getInstance());
        documentView.getDocumentLayoutParams().setHyphenated(true);
    }
}

Thank you hope you are don't mind I'm not good in code. :)

**Comment by bluejamesbond** [comment]
Provide screenshot.

**Comment by bluejamesbond** [comment]
It should look more like this:

```java
package com.cambobox.documentview;

import android.app.Activity;
import android.os.Bundle;

import com.bluejamesbond.text.DocumentView;
import com.bluejamesbond.text.hyphen.SqueezeHyphenator;
import com.bluejamesbond.text.style.TextAlignment;

public class MainActivity extends Activity {@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		
		// set layout
		setContentView(R.layout.activity_main);
        
        // text you want
		String text = "សៀវភៅដំបូងដែលគ្រឹះស្ថាន «ប្រភពប្រាជ្ញា» បានបោះពុម្ពនោះ គឺជាស្នាដៃរបស់អ្នកនិពន្ធ ប៉ែន តារាឫទ្ធិ ដែលជាការបកស្រាយអំពីកណ្ឌអេភេសូរ។ ទោះបើអ្នកប្រាជ្ញខាងគម្ពីរ និង អ្នកនិពន្ធរូបនេះ បានចែកឋានប៉ុន្មានអាទិត្យមុនពេល ដែលសៀវភៅនេះបានចែកចាយក៏ដោយ ក៏ស្នាដៃរបស់អ្នកនិពន្ធ ប៉ែន តារាឫទ្ធិ នៅតែដក់ជាប់ក្នុងចិត្តមនុស្សគ្រប់ជំនាន់ តាមរយៈសៀវភៅនេះដែរ។ បច្ចុប្បន្ននេះ «ប្រភពប្រាជ្ញា» មានទីតាំងនៅផ្ទះលេខ១១អា ផ្លូវលេខ២០០២ សង្កាត់ទឹកថ្លា ខណ្ឌសែនសុខ រាជធានីភ្នំពេញ។ មានបុគ្គលិកពេពេលជាជនជាតិខ្មែរ១១នាក់ សុទ្ធសឹងតែជាអ្នកមានជំនាញខ្ពស់ក្នុងវិស័យបោះពុម្ពផ្សាយ។ នោះជានិមិត្តចុងក្រោយរបស់លោកស្ទីវចំពោះ «ប្រភពប្រាជ្ញា» ដែលចង់ឃើញគ្រីស្ទបរិស័ទខ្មែរ ដឹកនាំពន្ធ័កិច្ចបោះពុម្ពផ្សាយដ៏សំខាន់នេះឆ្ពោះទៅពេលអនាគតដោយប្រសិទ្ធភាព។";

        // create DocumentView
		DocumentView documentView = new DocumentView(this, DocumentView.PLAIN_TEXT);
		
		// set the properties
		documentView.getDocumentLayoutParams().setTextColor(0xffffffff);
		documentView.getDocumentLayoutParams().setTextTypeface(Typeface.DEFAULT);
		documentView.getDocumentLayoutParams().setTextSize(14);
		documentView.getDocumentLayoutParams().setTextAlignment(TextAlignment.JUSTIFIED);
		documentView.getDocumentLayoutParams().setInsetPaddingLeft(30f);
		documentView.getDocumentLayoutParams().setInsetPaddingRight(30f);
		documentView.getDocumentLayoutParams().setInsetPaddingTop(30f);
		documentView.getDocumentLayoutParams().setInsetPaddingBottom(30f);
		documentView.getDocumentLayoutParams().setLineHeightMultiplier(1f);
		documentView.getDocumentLayoutParams().setHyphenator(SqueezeHyphenator.getInstance());
		documentView.getDocumentLayoutParams().setHyphenated(true);
        
        // set text
		documentView.setText(text)
		
		// ****************** you have to edit this ******************
		((SomeLayout) findViewById(R.id.some_layout)).addView(documentView)
	}
}
```

**Comment by bpbunthoeun** [comment]
OK This is my Java screenshot:
![java](https://cloud.githubusercontent.com/assets/4226547/5831722/a066fe3a-a16a-11e4-8151-6d2656733592.jpg)

**Comment by bluejamesbond** [comment]
Ok. I provided u with the code in my last post. Try that out. 



—

**Comment by bpbunthoeun** [comment]
Thank you but please tell me what should I edit in your code? this is my XML : 

<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:paddingTop="15dp"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <com.bluejamesbond.text.DocumentView
            xmlns:ext="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/dc_view1"
            ext:documentView_textAlignment="justified"
            ext:documentView_textFormat="plain"
            ext:documentView_textSubPixel="true">

            </com.bluejamesbond.text.DocumentView>

    </LinearLayout>


</ScrollView>

**Comment by bpbunthoeun** [comment]
"Unfortunately, Document View has stopped" this is the message that I got when I run on my phone. and this some code that I edited 
 // ****************** you have to edit this ******************
        ((DocumentView) findViewById(R.id.dc_view1)).addView(documentView);
    }
Thank you..

**Comment by bluejamesbond** [comment]
You should study more about Android, but I will help you here.

**activity_main.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:paddingTop="15dp"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
  <LinearLayout
    android:id="@+id/main_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
</LinearLayout>
```

**MainActivity.java**
```java
package com.cambobox.documentview;

import android.app.Activity;
import android.os.Bundle;

import com.bluejamesbond.text.DocumentView;
import com.bluejamesbond.text.hyphen.SqueezeHyphenator;
import com.bluejamesbond.text.style.TextAlignment;

public class MainActivity extends Activity {
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		
		// set layout
		setContentView(R.layout.activity_main);
        
        // text you want
		String text = "សៀវភៅដំបូងដែលគ្រឹះស្ថាន «ប្រភពប្រាជ្ញា» បានបោះពុម្ពនោះ គឺជាស្នាដៃរបស់អ្នកនិពន្ធ ប៉ែន តារាឫទ្ធិ ដែលជាការបកស្រាយអំពីកណ្ឌអេភេសូរ។ ទោះបើអ្នកប្រាជ្ញខាងគម្ពីរ និង អ្នកនិពន្ធរូបនេះ បានចែកឋានប៉ុន្មានអាទិត្យមុនពេល ដែលសៀវភៅនេះបានចែកចាយក៏ដោយ ក៏ស្នាដៃរបស់អ្នកនិពន្ធ ប៉ែន តារាឫទ្ធិ នៅតែដក់ជាប់ក្នុងចិត្តមនុស្សគ្រប់ជំនាន់ តាមរយៈសៀវភៅនេះដែរ។ បច្ចុប្បន្ននេះ «ប្រភពប្រាជ្ញា» មានទីតាំងនៅផ្ទះលេខ១១អា ផ្លូវលេខ២០០២ សង្កាត់ទឹកថ្លា ខណ្ឌសែនសុខ រាជធានីភ្នំពេញ។ មានបុគ្គលិកពេពេលជាជនជាតិខ្មែរ១១នាក់ សុទ្ធសឹងតែជាអ្នកមានជំនាញខ្ពស់ក្នុងវិស័យបោះពុម្ពផ្សាយ។ នោះជានិមិត្តចុងក្រោយរបស់លោកស្ទីវចំពោះ «ប្រភពប្រាជ្ញា» ដែលចង់ឃើញគ្រីស្ទបរិស័ទខ្មែរ ដឹកនាំពន្ធ័កិច្ចបោះពុម្ពផ្សាយដ៏សំខាន់នេះឆ្ពោះទៅពេលអនាគតដោយប្រសិទ្ធភាព។";

        // create DocumentView
		DocumentView documentView = new DocumentView(this, DocumentView.PLAIN_TEXT);
		
		// set the properties
		documentView.getDocumentLayoutParams().setTextColor(0xffffffff);
		documentView.getDocumentLayoutParams().setTextTypeface(Typeface.DEFAULT);
		documentView.getDocumentLayoutParams().setTextSize(14);
		documentView.getDocumentLayoutParams().setTextAlignment(TextAlignment.JUSTIFIED);
		documentView.getDocumentLayoutParams().setInsetPaddingLeft(30f);
		documentView.getDocumentLayoutParams().setInsetPaddingRight(30f);
		documentView.getDocumentLayoutParams().setInsetPaddingTop(30f);
		documentView.getDocumentLayoutParams().setInsetPaddingBottom(30f);
		documentView.getDocumentLayoutParams().setLineHeightMultiplier(1f);
		documentView.getDocumentLayoutParams().setHyphenator(SqueezeHyphenator.getInstance());
		documentView.getDocumentLayoutParams().setHyphenated(true);
        
		 // set text
		documentView.setText(text)
		
		// add to layout
		((LinearLayout) findViewById(R.id.main_layout)).addView(documentView)
	}
}
```

**Comment by bpbunthoeun** [comment]
Yes, thank you very much you.. it is working ..... :+1:
