### ISSUE TITLE
Setting text with spannable, wont update unless i click and drag on textview

### ISSUE THREAD

**Issue by xbroak** [bluejamesbond/TextJustify-Android#61]
private Spannable highlightString(String original, String search) {
        String rep = original;
        String newS = rep.replace(search, "<font color='red'>" + search + "</font>");
        ArticleBuilder amb = new ArticleBuilder();
        amb.append(
                newS
                , false, new RelativeSizeSpan(1f), new JustifiedSpan()
        );
        return amb;
        }

I am setting the text of my document view using the above which results in:

http://puu.sh/fepY7/a2edfbad2a.png

However, when i select a new line to highlight, NOTHING happens, setting the text view to ANY content, normal spannable string or otherwise, the view refuses to update, the only way i can get it to show the new value is to tap and drag on the view, how peculiar?

Thanks!

**Comment by bluejamesbond** [comment]
@xbroak Just call `documentView.requestLayout()`.

**Comment by xbroak** [comment]
I tried that! Nothing.

------ Original Message ------

**Comment by bluejamesbond** [comment]
Which version? 



—

**Comment by xbroak** [comment]
Latest

------ Original Message ------

**Comment by xbroak** [comment]
Weird, i am seeing different responses in the email notifications! how strange. 

compile 'com.github.bluejamesbond:textjustify-android:2.0.8'

That's the version, just fyi

**Comment by xbroak** [comment]
The only code is the documentview example on the wiki and the code i've pasted in my original post :)

**Comment by bluejamesbond** [comment]
I think I know the issue. I don't have a computer near me. Try calling 'documentView.invalidateCache()' right after you set the updated text. 



—

**Comment by bluejamesbond** [comment]
so it should look like this. 

'''
D.setText
D.invalidateCache
D.requestLayout
'''

**Comment by xbroak** [comment]
Hi, sorry to respond so late, it seems that 'invalidateCache' is not a defined method/public

**Comment by xbroak** [comment]
Just tried using destroyCache(); in its place, which does actually make it update! just only the first time, when attempting to set the text a second time, it reverts back to the old behaviour!

**Comment by xbroak** [comment]
Well. It seems that it's as simple as calling 'invalidate' after setting the text. Seems to update as desired now, very peculiar though?

**Comment by bluejamesbond** [comment]
@xbroak You don't need to do any of that anymore. Just set the text and it should change. Use version `2.0.9`

**Comment by xbroak** [comment]
I'm afraid, it is not fixed!

**Comment by xbroak** [comment]
Seems to be doing it all over again for some reason, my fix just stopped working.

**Comment by bluejamesbond** [comment]
Which version are you using?

**Comment by xbroak** [comment]
(Just updated the comment above)

I'm using the latest (2.1.0)

**Comment by bluejamesbond** [comment]
I think you should revert back to tge last working version I'll notify you when I can confirm the sokution.

**Comment by xbroak** [comment]
The weird thing is, even moving back to the old version seems to be doing it now. I literally changed nothing.

**Comment by xbroak** [comment]
I have a feeling i was just getting lucky before and the problem only happens at random.

**Comment by bluejamesbond** [comment]
If you can post a video. That would be the best! 



—

**Comment by sigrlami** [comment]
@xbroak you should try to call `invalidate()` on your DocumentView, I've got almost same problem and this helped. Somehow `requestLayout()` doesn't force to redraw view

**Comment by Edonfreiner** [comment]
Is there any fix for this yet I am trying to change the inline background for the DocumentView
