### ISSUE TITLE
TextJustify isn't support Thai language?

### ISSUE THREAD

**Issue by akexorcist** [bluejamesbond/TextJustify-Android#63]
I like this library but when I try with Thai language. It isn't show any text.

**Comment by bluejamesbond** [comment]
I am not sure why this would happen. Have you tried using just English and seeing if it displays?

**Comment by akexorcist** [comment]
No problem for english

**Comment by sigrlami** [comment]
@akexorcist 
Provide more info. Here is working Thai DocumentView
![subitems](https://cloud.githubusercontent.com/assets/1771634/8125154/d029131a-10eb-11e5-88c3-33ab838b6482.png)

**Comment by akexorcist** [comment]
@sigrlami Yeah. It's worked but still have a problem on justify text.

**Comment by sigrlami** [comment]
@akexorcist you need to close this issue and create new one with specifics of your problem
