### ISSUE TITLE
OutOfMemory Error with DocumentView inside ListView

### ISSUE THREAD

**Issue by DivineCake** [bluejamesbond/TextJustify-Android#64]
Hi Mathew Kurian,
I'm getting an OutOfMemory error on DocumentView when running the app on my tablet (Nexus10). It is odd because I tested it on weaker devices (HTC One V) and is working just fine. Is this a known issue? 
![screen shot 2015-02-04 at 8 10 32 pm](https://cloud.githubusercontent.com/assets/10678997/6040207/20ae20a6-acaa-11e4-9395-7ae85e2d749b.png)

**Comment by bluejamesbond** [comment]
@DivineCake 

Try disabling the cache and see what happens

```java
docView.setCacheConfig(CacheConfig.NO_CACHE)
```

**Comment by DivineCake** [comment]
Hi Mathew,
I tried to disable the cache as you suggested, holder.description.setCacheConfig(DocumentView.CacheConfig.NO_CACHE);
It crashes with the following error:
![screen shot 2015-02-04 at 11 22 08 pm](https://cloud.githubusercontent.com/assets/10678997/6043076/ba4cfb00-acc4-11e4-80d3-487337333765.png)

Thanks!

**Comment by bluejamesbond** [comment]
This is unusual. I will review the code soon and let you know. 



—

**Comment by bluejamesbond** [comment]
@DivineCake You caught a good bug. This would rarely happen in normal usage. Thanks! Use version `2.1.0`

**Comment by DivineCake** [comment]
Now working on the Nexus 10 by disabling cache! Thank you so much Mathew.

**Comment by DivineCake** [comment]
Hi Mathew,

After testing again, I noticed that on version 2.1.0, PressableDocumentView is not working as intended.
I tested by reverting back to version 2.0.8 and true enough, PressableDocumentView is working just fine.
