### ISSUE TITLE
keystore password

### ISSUE THREAD

**Issue by WebnetMobile** [bluejamesbond/TextJustify-Android#78]
Are you sure you wanted this in public repo?:

                    keyAlias 'bluejamesbond'
                    keyPassword 'Mkone123*'
                    storeFile file('C:/release.keystore.jks')
                    storePassword 'Mkone123*'

https://github.com/bluejamesbond/TextJustify-Android/blob/master/sample/build.gradle

**Comment by bluejamesbond** [comment]
Thank you for bringing this to my attention. It seems like I left it in there accidentally. I will remove it asap.
