### ISSUE TITLE
default Typeface should be Roboto

### ISSUE THREAD

**Issue by ciscorucinski** [bluejamesbond/TextJustify-Android#90]
I have just used this library and just simply justified plain text, and noticed that the font used by this library is not the standard typeface. If you look close, the text is jagged, and does not look like the other Roboto text in my app

**Comment by ciscorucinski** [comment]
Also, is there no way to programmatically set the Typeface? The wiki is apparently out-of-date, and the .setTypeface method does not exist

**Comment by bluejamesbond** [comment]
Refer to this: https://github.com/bluejamesbond/TextJustify-Android/blob/6dc6b9297d3a5a97dc4422d5405c3430b6353593/sample/src/main/java/com/bluejamesbond/text/sample/helper/TestActivity.java#L71

I am a bit busy these days but I will gladly accept a PR if you want to update the docs.

**Comment by ciscorucinski** [comment]
Do you also allow for antialiasing? 

Test:
- Place a DocumentView above a TextView
- Set both to the same text
- Run app and take a screenshot
- In gallary, zoom into the text close

You will see that the DocumentView has jagged Text, but the TextView is smooth. This is the case even when the same font is used.

**Comment by ciscorucinski** [comment]
Top black text is the Document view
Bottom greyish  text is Text view. 

![screenshot_2015-08-10-05-22-16](https://cloud.githubusercontent.com/assets/8707125/9156796/4144caa4-3f21-11e5-823c-4d61da1ab6b8.png)

**Comment by ciscorucinski** [comment]
found it. Things are good now with this issue
