### ISSUE TITLE
How to use hyphenation with textview?

### ISSUE THREAD

**Issue by aselims** [bluejamesbond/TextJustify-Android#99]
I do not need the DocumentView. I just want have hyphenation in TextView.
Thanks.

**Comment by bluejamesbond** [comment]
At the moment, they are closely intertwined because you have to manually draw out the tokens. So, any implementation must extend textview.

**Comment by aselims** [comment]
Sorry I do not understand. Could you please elaborate more?

**Comment by bluejamesbond** [comment]
I apologize for the late response. Generally, all the content needs to be drawn out manually here which means the Hyphenation is built exclusively for just that. So, you cannot use it with TextView. Please reopen if you have any more questions.
